import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
function git(...args) {
  try {
    return execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}
const commit = String(process.env.HANDRAIL_ENHANCEMENT_REPORTER_SDK_COMMIT || git("rev-parse", "HEAD")).trim();
const exactTag = commit ? git("describe", "--exact-match", "--tags", commit) : "";
const releaseRef = String(process.env.HANDRAIL_ENHANCEMENT_REPORTER_SDK_REF || (exactTag === `v${manifest.version}` ? `refs/tags/${exactTag}` : commit ? `commit:${commit}` : `refs/tags/v${manifest.version}`)).trim();
if (commit && !/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/iu.test(commit)) throw new Error("Enhancement reporter release commit must be a full Git commit.");
const output = resolve(root, "src/generated/release.ts");
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, [
  "// Generated by scripts/generate-release.mjs. Do not edit.",
  `export const GENERATED_PACKAGE_NAME = ${JSON.stringify(manifest.name)} as const;`,
  `export const GENERATED_PACKAGE_VERSION = ${JSON.stringify(manifest.version)} as const;`,
  `export const GENERATED_PACKAGE_COMMIT = ${JSON.stringify(commit)} as const;`,
  `export const GENERATED_PACKAGE_RELEASE_REF = ${JSON.stringify(releaseRef)} as const;`,
  "",
].join("\n"), "utf8");
